title: "Easygoing"
subtitle: "Welcome to my blog"
description: "Blog description goes here"

exclude:
  - _compress_images_cache.yml

footer: "Copyright: Ryan Loi"

imageoptim:
  pngout: false
  svgo: false
  verbose: false

navigation:
  - title: "Home"
    url: "/"

  - title: "Posts"
    url: "/posts"

  - title: "About"
    url: "/about"

permalink: /:title

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-compress-images
  - jekyll-sitemap

paginate: 10
paginate_path: "/posts/:num"